[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "simple-drone-detector"
version = "0.1.0"
description = "Simple Drone Detector (SDD)"
requires-python = ">=3.10"

[tool.setuptools.packages.find]
where = ["src"]
